version: '3.9'

services:
  mssql:
    container_name: flash-mssql
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "flashSApa55word"
    ports:
      - "1433:1433"
    restart: always